version: '2'

volumes:
  postgres_data_dev: {}
  postgres_backup_dev: {}

services:
  postges:
    container_name: postgres_server
    build: ./docker_compose/postgres
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
      - postgres_backup_dev:/backups
    env_file: .env

  node:
    container_name: node_server
    build:
      context: .
      dockerfile: ./docker_compose/node/development/Dockerfile
    command: /start.sh
    volumes:
      - .:/app
    ports:
      - "3000:3000"

    django:
      container_name: django_server
      build:
        context: .
        dockerfile: ./docker_compose/django/development/Dockerfile
      command: /start.sh
      depends_on:
        - postgres
        - node
      env_file: .env
      volumes:
        - .:/app
      ports:
        - "8000:8000"
      links:
        - postgres

